# Site
repository: backlo/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: 이인권
title: 성장에 목마른 웹 백앤드 신입 개발자
email: hjun4512@gmail.com
website: http://poododang.tistory.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  backlo
linkedin_username: 인권-이-074b11197

# Additional icon links
# additional_links:
# - title: 
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# About Me Section
about_profile_image: images/resume_profile.jpeg
about_title: Introduce
about_content: |
  ***1. ‘동의되지 않는 권위에 굴복하지 말자’는 저의 좌우명 입니다.***

  단순히 ‘카더라’로 지식을 습득하는 것이 아닌, 깊게 공부하자는 목표를 세웠습니다.
  즉 하나의 기능을 응용까지 펼칠 수 있는 이러한 역량을 가지고 싶어 노력하고 있습니다.

  ***2. 새로운 도전을 두려워하지 않습니다.***

  공모전, 외부 프로젝트 등 다양한 도전을 통해 스스로의 성장을 멈추지 않고있습니다.
  새로운 기술을 학습하고 적용하는 과정을 거치며 그 과정에 흥미를 느끼고 꾸준히 발전하고 있습니다.

  ***3. 불편함을 그냥 지나치지 않습니다.***

  비효율적인 프로세스나 반복되는 일이 발생하면 어떻게든 해결하려는 의지를 가지고 있습니다.
  나보단 남을 생각하며 팀원들이 불편을 해소시켜주려 하고 있습니다. 
  또한 문제 발생을 방지하기 위해 테스트 작성을 게을리 하지 않습니다.

  ***4. 공유 문화와 적극적인 협업을 좋아합니다.***

  팀 프로젝트는 팀원들이 한 몸같이 일한다고 생각해 팀원과 적극적인 커뮤니케이션으로 협업을 추구합니다.
  또한 친구들과 같이 [스터디](https://github.com/backlo-study-programing)를 진행하여 함께 모르는 부분들을 채워나갔습니다.

# Skill Section
skill_title: Skill Set

# Activity Section
activity_image: images/activities.png
activity_title: Activities
    
# Projects Section
projects_title: Project 

# Education Section
education_title: Education 

# OpenSource Section
open-soutce_title: OpenSource

# Experience Section
experience_title: Experience 

#Career Section
career_title: Career 

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
